defenseunicorns/uds-runtime

README.md, ui/src/app.postcss, ui/src/lib/components/DataTable/component.svelte, ui/src/lib/features/k8s/daemonsets/store.ts, ui/src/lib/features/k8s/deployments/store.ts, ui/src/lib/features/k8s/events/store.ts, ui/src/lib/features/k8s/namespaces/store.ts, ui/src/lib/features/k8s/pods/store.ts, ui/src/lib/features/k8s/statefulsets/store.ts, ui/src/lib/features/k8s/store.ts, ui/src/lib/features/k8s/types.ts, ui/src/lib/features/k8s/uds-packages/store.ts, ui/src/lib/types.ts, ui/src/routes/monitor/pepr/[[stream]]/+page.svelte
Working on some best practices related issues
- #19
=> refactor: moving common row to types folder

ui/src/lib/components/DataTable/component.svelte
Turns off autocomplete for datatable component
- #21
=> fix: turn off autocomplete for datatable

.pre-commit-config.yaml, tasks.yaml, ui/.prettierrc, ui/eslint.config.js, ui/package-lock.json, ui/package.json, ui/playwright.config.ts, ui/src/lib/features/k8s/daemonsets/store.ts, ui/src/lib/features/k8s/deployments/store.ts, ui/src/lib/features/k8s/events/store.ts, ui/src/lib/features/k8s/namespaces/store.ts, ui/src/lib/features/k8s/pods/metrics/utils.test.ts, ui/src/lib/features/k8s/pods/store.ts, ui/src/lib/features/k8s/statefulsets/store.ts, ui/src/lib/features/k8s/store.ts, ui/src/lib/features/k8s/uds-packages/store.ts, ui/src/routes/monitor/pepr/[[stream]]/+page.svelte, ui/tests/monitor.spec.ts, ui/tests/navigation.spec.ts
- adds feature to export monitor/pepr data as a JSON file
- adds typescript section pre-commit
- adds import optimizer prettier plugin (specifically added to remove unused imports)
- adds Maru task for builds
- #23
=> feat: export pepr data stream

ui/src/lib/components/DataTable/component.svelte
Prevent errors if a row has a null value when rendering the DataTable component
=> fix(ui): prevent error on null fields in DataTable component

.gitignore, ui/src/routes/monitor/pepr/[[stream]]/+page.svelte
fixes bug where we were getting an additional pepr subscriber everytime we would navigate away from the pepr view and back.
fixes #37
=> fix(ui): pepr monitor unsubscriber

pkg/api/resources/cache.go, pkg/api/start.go, ui/src/lib/components/DataTable/component.svelte, ui/src/lib/features/k8s/cluster-ops/priority-classes/component.svelte, ui/src/lib/features/k8s/cluster-ops/priority-classes/component.test.ts, ui/src/lib/features/k8s/cluster-ops/priority-classes/store.ts, ui/src/lib/features/k8s/index.ts, ui/src/routes/(resources)/cluster-ops/priority-classes/+page.svelte
Adding Priority Classes view
- #32
=> feat(ui): adding cluster ops priority classes view

ui/src/lib/features/k8s/index.ts, ui/src/lib/features/k8s/storage/persistentvolumes/component.svelte, ui/src/lib/features/k8s/storage/persistentvolumes/component.test.ts, ui/src/lib/features/k8s/storage/persistentvolumes/store.ts, ui/src/routes/(resources)/storage/persistent-volumes/+page.svelte
Adds PersistentVolume view
Lens:
UDS:
- #58
=> feat: adds pv view

ui/src/lib/features/k8s/cluster-ops/mutatingwebhooks/component.svelte, ui/src/lib/features/k8s/cluster-ops/mutatingwebhooks/component.test.ts, ui/src/lib/features/k8s/cluster-ops/mutatingwebhooks/store.ts, ui/src/lib/features/k8s/index.ts, ui/src/routes/(resources)/cluster-ops/mutating-webhooks/+page.svelte
=> feat(ui): add cluster-ops/mutating-webhooks view

ui/src/lib/features/k8s/index.ts, ui/src/lib/features/k8s/storage/storageclasses/component.svelte, ui/src/lib/features/k8s/storage/storageclasses/component.test.ts, ui/src/lib/features/k8s/storage/storageclasses/store.ts, ui/src/routes/(resources)/storage/storage-classes/+page.svelte
Adds `StorageClass` view
Lens:
UDS:
- #60
=> feat: add storageclasses view

pkg/api/sse/bind.go, pkg/api/sse/sse.go, pkg/api/start.go, pkg/api/udsmiddleware/compress.go, ui/tests/sse.spec.ts
Refactors gzip compression to a middleware
|                                                       | No Compression | Compression |   |   |
|-------------------------------------------------------|----------------|-------------|---|---|
| /api/v1/resources/workloads/pods?once=true&dense=true | 121kB          | 15.9kB      |   |   |
- #85
=> fix: use middleware for compression

pkg/api/resources/cache.go, pkg/api/start.go, ui/src/lib/features/k8s/cluster-ops/limit-ranges/component.svelte, ui/src/lib/features/k8s/cluster-ops/limit-ranges/component.test.ts, ui/src/lib/features/k8s/cluster-ops/limit-ranges/store.ts, ui/src/lib/features/k8s/cluster-ops/priority-classes/store.ts, ui/src/lib/features/k8s/index.ts, ui/src/routes/(resources)/cluster-ops/limit-ranges/+page.svelte
Adding cluster ops limit ranges view
- #47
=> feat: adding cluster ops limit ranges view

ui/src/lib/features/k8s/index.ts, ui/src/lib/features/k8s/networks/endpoints/component.svelte, ui/src/lib/features/k8s/networks/endpoints/component.test.ts, ui/src/lib/features/k8s/networks/endpoints/store.ts, ui/src/routes/(resources)/networks/endpoints/+page.svelte
=> feat(ui): endpoints view

ui/src/lib/features/k8s/index.ts, ui/src/lib/features/k8s/networks/network-policies/component.svelte, ui/src/lib/features/k8s/networks/network-policies/component.test.ts, ui/src/lib/features/k8s/networks/network-policies/store.ts, ui/src/lib/features/k8s/networks/services/store.ts, ui/src/routes/(resources)/networks/network-policies/+page.svelte
=> feat(ui): networkpolicies view

pkg/api/resources/cache.go, pkg/api/start.go, ui/src/lib/features/k8s/cluster-ops/pod-disruption-budgets/component.svelte, ui/src/lib/features/k8s/cluster-ops/pod-disruption-budgets/component.test.ts, ui/src/lib/features/k8s/cluster-ops/pod-disruption-budgets/store.ts, ui/src/lib/features/k8s/index.ts, ui/src/routes/(resources)/cluster-ops/pod-disruption-budgets/+page.svelte
Add api and view for pod disruption budgets
- #48
=> feat: add pod disruption budgets view

ui/src/lib/features/k8s/cluster-ops/validatingwebhooks/component.svelte, ui/src/lib/features/k8s/cluster-ops/validatingwebhooks/component.test.ts, ui/src/lib/features/k8s/cluster-ops/validatingwebhooks/store.ts, ui/src/lib/features/k8s/index.ts, ui/src/routes/(resources)/cluster-ops/validating-webhooks/+page.svelte
=> feat(ui): adds validatingwebhooks view

ui/src/lib/features/k8s/store.ts
Formats age to be prettier
- https://github.com/defenseunicorns/uds-runtime/issues/66
=> feat(ui): format age with more detail

ui/src/lib/features/toast/component.svelte, ui/src/lib/features/toast/component.test.ts, ui/src/lib/features/toast/index.ts, ui/src/lib/features/toast/store.test.ts, ui/src/lib/features/toast/store.ts, ui/src/routes/+layout.svelte
Add the ability to create toast messages using `addToast()` to write to a common store
- #115
=> feat(ui): add toast for status messages

.github/workflows/tag-and-release.yaml
more permissions for release ([based on uds-core](https://github.com/defenseunicorns/uds-core/blob/main/.github/workflows/tag-and-release.yaml))
=> fix(ci): more permissions for release

release-please-config.json
=> fix: remove alpha from release

.github/workflows/dependency-review.yml, .github/workflows/pr-tests.yaml, .github/workflows/scan-codeql.yaml, .github/workflows/scan-lint.yaml, .github/workflows/scorecard.yaml
enable release-please PRs to run workflows
Thanks @mjnagel !
=> fix: enable release-please PRs to run workflows

tasks/test.yaml, ui/playwright.config.ts, ui/tests/packages/podinfo/exemptions.yaml, ui/tests/packages/podinfo/uds-package.yaml, ui/tests/packages/podinfo/values.yaml, ui/tests/packages/podinfo/zarf.yaml, ui/tests/sse.spec.ts, ui/tests/zarf.yaml
speed up e2e tests with minimal cluster
=> chore: speed up e2e tests with minimal cluster

.github/workflows/commitlint.yaml, .github/workflows/nightly-release.yaml, .github/workflows/pr-tests.yaml, .gitignore, hack/zarf.yaml, release-please-config.json, tasks.yaml, tasks/build.yaml
Adds nightly releases
https://github.com/defenseunicorns/uds-runtime/releases/tag/nightly-unstable
https://github.com/defenseunicorns/uds-runtime/issues/153
=> feat(ci): add nightly releases

.github/workflows/pr-tests.yaml, .github/workflows/scan-lint.yaml, tasks/setup.yaml, tasks/test.yaml
install Istio CRDs for minimal e2e tests
=> chore: install Istio CRDs for minimal e2e tests

ui/playwright.config.ts, ui/tests/navigation.spec.ts, ui/tests/packages/podinfo/zarf.yaml
Adds some basic e2e testing for ensuring our test data running in the cluster shows up in the UI
=> chore: adds basic e2e tests

pkg/api/resources/list.go, ui/src/lib/components/k8s/DataTable/component.svelte
=> fix(ui): restart and node columns in pod table

ui/src/lib/components/k8s/DataTable/component.svelte, ui/tests/table.spec.ts
Testing the search functionality and drop down selections. This can be achieved by trying to search for a term while selecting the different drop down options of 
* Anywhere
* Metadata
* Name
- #184
- #185
=> feat: adding e2e tests for search and dropdown selections

.github/workflows/nightly-release.yaml
=> fix: correct nightly working dir

adr/0001-api-testing.md
=> chore: api testing adr

.github/test-infra/packer/install-tools.sh, .github/test-infra/terraform/main.tf
adds SSM to ephemeral instance so we can debug issues
=> chore: adds ssm to runtime-canary

chart/values.yaml, hack/nightly/nightly-values.yaml
update `pullPolicy` value default
=> chore: update pullPolicy

.github/actions/setup/action.yaml
=> chore: tag uds cli install for renovate

.github/test-infra/terraform/setup.sh, .github/test-infra/terraform/variables.tf, .gitignore
For easier debugging via SSM, give ssm-user more permissions
=> fix: give ssm-user more permissions

ui/src/app.html, ui/src/routes/+layout.svelte
Fixing issue for Flash Of Unstyled Content (FOUC)
- #208
=> fix: fixing FOUC issue

CONTRIBUTING.md
Adding guidelines for how to use playwright locators when adding front end tests
- #237
=> chore: adding contributing instructions for front end testing locators

ui/package-lock.json, ui/package.json, ui/src/lib/features/k8s/cluster-overview/component.svelte
Fixing an issue with the chart in the overview page not being destroyed on component dismount
- #241
=> fix: fixing issue with chart not being destroyed onDestroy

Dockerfile
the names for the go binaries were updated, need to update the dockerfile to match
=> fix(api): dockerfile for releasing go binaries

.github/workflows/tag-and-release.yaml
chore: add v to release workflow
=> chore: add v to release workflow

README.md
=> docs: fix deploy commands

ui/src/lib/features/k8s/applications/endpoints/store.ts, ui/src/lib/features/k8s/cluster-ops/hpa/store.ts, ui/src/lib/features/k8s/cluster-ops/limit-ranges/store.ts, ui/src/lib/features/k8s/cluster-ops/pod-disruption-budgets/store.ts, ui/src/lib/features/k8s/cluster-ops/resource-quotas/store.ts, ui/src/lib/features/k8s/configs/configmaps/store.ts, ui/src/lib/features/k8s/configs/secrets/store.ts, ui/src/lib/features/k8s/configs/uds-exemptions/store.ts, ui/src/lib/features/k8s/configs/uds-packages/store.ts, ui/src/lib/features/k8s/networks/endpoints/store.ts, ui/src/lib/features/k8s/networks/network-policies/store.ts, ui/src/lib/features/k8s/networks/services/store.ts, ui/src/lib/features/k8s/networks/virtualservices/store.ts, ui/src/lib/features/k8s/storage/persistentvolumes/store.ts, ui/src/lib/features/k8s/workloads/cronjobs/store.ts, ui/src/lib/features/k8s/workloads/daemonsets/store.ts, ui/src/lib/features/k8s/workloads/deployments/store.ts, ui/src/lib/features/k8s/workloads/jobs/store.ts, ui/src/lib/features/k8s/workloads/pods/store.ts, ui/src/lib/features/k8s/workloads/statefulsets/store.ts
update the default sorting for tables with namespace columns
- #305
=> refactor(ui): update the default sorting for tables

ui/src/lib/utils/descriptions.ts
Updates to clarify wording and note metrics targets.
=> chore: update description for UDS Package

ui/src/lib/features/k8s/workloads/pods/component.svelte, ui/src/lib/features/k8s/workloads/pods/component.test.ts, ui/src/lib/features/k8s/workloads/pods/store.ts
Updating the Pods table to use "usage" instead of "metrics"
- #311
=> feat(ui): updating pods table column name

ui/src/lib/components/ProgressBar/component.svelte
Fixing issue with the progress bar for CPU and Memory not working
- #373
=> feat(ui): fixing issue with progress bar

ui/src/lib/components/k8s/Event/EventsOverviewWidget.svelte, ui/src/lib/components/k8s/Status/component.svelte, ui/src/lib/features/k8s/events/component.test.ts, ui/src/lib/features/k8s/events/store.ts, ui/src/lib/features/k8s/helpers.ts, ui/src/lib/features/k8s/storage/persistentvolumeclaims/status/component.svelte
Adds color to the Type column in Events table.
Resolves #419
=> chore(ui): add status colors for event type in events table

CODEOWNERS, LICENSE
Updates license to AGPLv3 and updates codeowners
=> chore: license to AGPLv3 and update codeowners

CODEOWNERS
Ensures @austenbryan and @jeff-mccoy can update `LICENSE` and `LICENSING.md`
=> chore: updates codeowners for both license files

ui/package.json
=> chore: bumps uds-types version

ui/package-lock.json, ui/package.json
Forgot to bump package-lock in last PR 🤦
=> chore: bump uds-types in package lock

pkg/api/resources/cache_test.go
added test for setWatchErrorHandler logic in cache.go
=> chore: watch error handler test

chart/templates/deployment.yaml, chart/values.yaml
Adds security context values to Helm chart
=> feat: adds security context to Helm chart

src/pkg/api/start.go
Lock interfaces when serving api to Localhost
Resolves #440
Before: got 200 response with index.html
After: received connection refused
=> chore(api): bind only to localhost interface on serve

README.md
Make sure Doug logo does not get intersected by the Quickstart section horizontal line.
=> fix: readme logo cutoff
