defenseunicorns/uds-runtime

- ui/src/lib/features/k8s/configs/uds-exemptions/store.ts
- ui/src/lib/features/k8s/index.ts
- ui/tests/navigation.spec.ts
Fixing an issue where the end to end navigation tests broke due to a renaming of the route key name/ title
- #29
> test: update e2e to match new routes

- ui/src/lib/features/k8s/index.ts
- ui/src/lib/features/k8s/storage/persistentvolumeclaims/component.svelte
- ui/src/lib/features/k8s/storage/persistentvolumeclaims/component.test.ts
- ui/src/lib/features/k8s/storage/persistentvolumeclaims/store.ts
- ui/src/routes/(resources)/storage/persistent-volume-claims/+page.svelte
adds `PersistentVolumeClaim` view
Lens:
UDS:
- #59
> feat(ui): add pvc view

- pkg/api/resources/cache.go
- pkg/api/start.go
- ui/src/lib/features/k8s/cluster-ops/resource-quotas/component.svelte
- ui/src/lib/features/k8s/cluster-ops/resource-quotas/component.test.ts
- ui/src/lib/features/k8s/cluster-ops/resource-quotas/store.ts
- ui/src/lib/features/k8s/index.ts
- ui/src/routes/(resources)/cluster-ops/resource-quotas/+page.svelte
Adding cluster ops limit ranges view
- #49
> feat(ui): adding cluster ops resource quotas view

- ui/src/lib/components/Link/component.svelte
- ui/src/lib/components/k8s/DataTable/component.svelte
- ui/src/lib/features/k8s/applications/endpoints/component.test.ts
- ui/src/lib/features/k8s/applications/endpoints/store.ts
- ui/src/lib/features/k8s/configs/uds-packages/links/component.svelte
- ui/src/lib/features/k8s/test-helper.ts
Previously, endpoints in Pending state were shown as "[Object object]", this updates them to show as "Pending"
> fix: empty endpoints are shown as Pending

- ui/src/lib/features/k8s/workloads/pods/component.test.ts
- ui/src/lib/features/k8s/workloads/pods/status/component.svelte
- ui/src/lib/features/k8s/workloads/pods/status/component.test.ts
- ui/src/lib/features/k8s/workloads/pods/store.ts
add color to status
based colors on https://www.figma.com/design/zmKcJ9Xin7ChzyGy6RCFLe/UDS-Runtime-(UI%2FCLI)?node-id=3723-2949&t=SFK3K04QAwtQF1VD-0
Resolves #169
I explored adding the style to the column (e.g. ['status, '<style>']) but as it works atm, that will only handle 1 status case. so went for a component that handles the style logic based on status instead.
> fix: pod status color

- ui/src/lib/components/k8s/DataTable/component.svelte
- ui/src/lib/features/k8s/cluster-overview/component.svelte
- ui/tests/navigation.spec.ts
- ui/tests/sse.spec.ts
- ui/tests/table.spec.ts
Testing the namespace functionality. This can be achieved by clicking on a row which has a namespace action or by selection a namespace from the drop down on the table header
- #180 
Here are some screenshots of what the ID's generate to with the code used to generate them. In this case the resource name is being used i.e. Pod to generate ID's specific to this resource on the DataTable. Every table will have unique ID's based on the resource for these 2 items (i.e. header results and drop down option)
```Svelte
<div class="table-header">
<span class="dark:text-white" data-testid={`${name}-table-header`}>{name}</span>
{#if isFiltering}
<span class="dark:text-gray-500 pl-2" data-testid={`${name}-table-header-results`}>
(showing {$rows.length} of {$numResources})
</span>
{:else}
<span …
```
> feat: adding e2e tests for DataTable

- ui/src/lib/features/k8s/workloads/deployments/component.test.ts
- ui/src/lib/features/k8s/workloads/deployments/store.ts
Workloads > Deployments > Available column was showing a single available replica even if there were more than 1 because it was looking at the number of `type: 'Available'` conditions in `.status.conditions`. This changes the logic to read the `availableReplicas` field instead.
Resolves #173
> fix(ui): deployments table not showing accurate available count

- chart/templates/uds-package.yaml
- chart/values.yaml
- hack/nightly/nightly-values.yaml
Configure package host so nightly can be set to `runtime-canary` for ephemeral cluster.
> chore: make uds package host configurable for nightly

- pkg/api/resources/list.go
This PR strips annotations from sparse datasets to avoid excess data and prevent leaky secret data with the `kubectl.kubernetes.io/last-applied-configuration` [annotation](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/). It also corrects the mutation of the original object by `extractSparseObject` by making a deep copy of the object metadata prior to modifying it. Removal of `managedFields` was moved to the source function to affect all resource views.
> feat(api): strip annotations from sparse resources

- Dockerfile
Fixes the docker container failure by moving `API_AUTH_DISABLED` out of CMD so that ./app/runtime can be executed without needing to bring in `"sh", "-c"`.
> fix: docker container run failure

- ui/src/routes/monitor/pepr/[[stream]]/+page.svelte
Updating the skeleton table to resemble the actual data for the Pepr stream data
- #285
> refactor(ui): updating skeleton for pepr table

- ui/src/lib/components/k8s/Drawer/component.svelte
The drawer tab has an issue when the content is taller than the height of the container where it cuts off the bottom of the content
This PR addresses that issue
- #292
> feat(ui): adjusting drawer margins

- ui/src/routes/monitor/pepr/[[stream]]/+page.svelte
- ui/tests/monitor.spec.ts
- ui/tests/table.spec.ts
- Adds searching + sorting to Pepr table
- Aligns Pepr table with the rest of the app
Noting that I intentionally duplicated code from our `Datatable` component. That component is already pretty complex and I felt that making it generic enough to handle the Pepr data would add even more complexity
Updated Pepr table:
- #296
> feat(ui): add functionality to Pepr table

- ui/src/lib/components/k8s/DataTable/component.svelte
- ui/src/lib/utils/cluster-check/cluster-check.test.ts
- ui/src/lib/utils/cluster-check/cluster-check.ts
Uses a custom event, dispatched from the cluster health check utility to the Datatable, for "cycling" the current store on cluster reconnection. 
**NOTE**: in a spike PR (#317), we tested using svelte's createEventDispatcher with a window event listener on the Datatable, which did not work. We then tried placing `on:cluster-reconnected={handler}` on calls to Datatable but that wouldn't work either because of the need to extract the handler out of Datatable, which needs access to the current stop() set by rows.start() inside Datatable.
* create cluster
* run backend
* run frontend
* re-create cluster of the same name
* watch pods in UI -- you should see an error toast and eventually a successfully reconnected toast and a small flash on the table and then any new updates happening to pods. …
> feat(ui): reload data view when cluster reconnection is successful

- ui/src/lib/features/k8s/cluster-overview/component.svelte
Fixes bug being seen specifically when looking at larger clusters where the app freezes/crashes if you try to load the cluster overview page  immediately after launching.
> fix: historical usage loading

- pkg/api/handlers.go
- pkg/api/start.go
- pkg/api/start_test.go
Fixes getCurrentContext() errors that occur when running the application in the cluster by not running reconnection handling in cluster and serving a different health check response to the UI.
Tested manually and confirmed works. Will be submitting a follow up PR with a nightly smoke test to catch this kind of thing. It was a lot of code changes for this PR though.
> fix(api): errors from trying to get kubecontext while in cluster

- pkg/test/api_test.go
Increases the context timeout for api route tests so that we increase the time for the go routine serving the SSE request to get data events back on networks with higher latency than local.
Resolves #345
> fix(api): flaky api tests

- pkg/test/api_test.go
Introduces retries with backoff and increased context timeouts to the api route test helper to fix flaky tests in CI.
> chore: api route test helper with retries and exponential backoff

- pkg/api/monitor/cluster.go
- pkg/api/monitor/cluster_test.go
- ui/src/lib/features/k8s/cluster-overview/component.svelte
- ui/tests/navigation.spec.ts
ensures pod counts are consistent between Overview and Pods pages
https://github.com/defenseunicorns/uds-runtime/issues/361
> fix: ensure pod counts are consistent

- README.md
- chart/templates/deployment.yaml
- chart/values.yaml
Makes the resource limits and requests configurable so users can adjust per environment needs. This also update the default resource limit to 1Gi.
resolves #368
> feat: make deployment resources configurable and up default memory

- ui/src/routes/monitor/pepr/[[stream]]/(details)/mutated-details/MutatedDetails.svelte
Fixing issue with text going outside of the tooltip due to Firefox not supporting `text-wrap: pretty`
Issue
- #293
> fix: fixing issue with firefox not supporting text-wrap: pretty

- ui/src/lib/components/ProgressBar/component.svelte
Fixing issue with memory bar still not showing color
This was because the css that is generated did not include the class we were using. Autoprefxr must have missed the class somehow
- #380
> fix: fixing memory bar for overview page

- chart/templates/uds-package.yaml
- go.mod
- go.sum
- pkg/api/auth/session.go
- pkg/api/auth/session_test.go
- pkg/test/api_test.go
- Performs group validation from the JWT received from Keycloak/Authservice.
- Removes deprecated api auth tests
- In addition to the unit tests, testing was performed by building a local Runtime image + Zarf pkg and deploying into a UDS Core dev cluster, then logging in via Google SSO to verify access
> feat(api): adds jwt group validation when in-cluster

- .github/actions/setup/action.yaml
- tasks/setup.yaml
- tasks/test.yaml
This adds authsvc to the slim-core deployment, which allows us to test authsvc protection for nightly and main releases while not bumping our runners to deploy full core. The latest versions of uds-k3d also require an updated version of k3d, so bumped to `5.7.4`.
> chore: update slim core with authsvc deployment and bump k3d version

- pkg/api/handlers.go
- ui/src/lib/features/toast/store.test.ts
- ui/src/lib/features/toast/store.ts
- ui/src/lib/utils/api-auth.ts
- ui/src/lib/utils/cluster-check/cluster-check.ts
- ui/src/routes/+page.svelte
- ui/vite.config.ts
- fixes typo in Vite config (`npm run dev` was broken)
- removes `token` param from URL when running locally
- de-dups toast messages
Resolves https://github.com/defenseunicorns/uds-runtime/issues/393
> chore: fix typo, clean URL, de-dup toast

- ui/eslint.config.js
- ui/src/lib/components/k8s/Drawer/component.svelte
Re-enables the eslint rule svelte/no-at-html-tags and ignores rule only for single instance where we're using DOMPurify.
Resolves #437
> chore(ui): re-enable svelte/no-at-html-tags rule

- Dockerfile
- src/pkg/api/docs/docs.go
- src/pkg/api/docs/swagger.json
- src/pkg/api/docs/swagger.yaml
- src/pkg/api/handlers.go
- src/pkg/api/start.go
- src/test/e2e/api_test.go
- ui/src/lib/utils/cluster-check/cluster-check.test.ts
- ui/src/lib/utils/cluster-check/cluster-check.ts
- ui/vite.config.ts
- renames `/health` -> `/cluster-check`
- adds a health check endpoint
Relates to https://github.com/defenseunicorns/uds-runtime/issues/442
> feat: adds health check

- ui/src/lib/components/ProgressBar/component.svelte
- ui/src/lib/components/StatsWidget/ProgressBarWidget.svelte
- ui/src/lib/components/StatsWidget/WithRightIconWidget.svelte
- ui/src/lib/components/k8s/Card/component.svelte
- ui/tests/local-auth.spec.ts
- ui/tests/navigation.spec.ts
Currently on the overview page if we try to navigate to Pods or Nodes page by clicking on the overview cards at the top, they do not navigate unless you click on the content area. 
This change, adds the ability to navigate by clicking anywhere on the card
- #484 
https://github.com/user-attachments/assets/ddfe4888-1d13-463a-a744-1533bb800f00
> feat(ui): update overview cards to navigate on click
